---

- name: ensure epel-release
  yum:
    name: epel-release
    state: latest

- name: ensure aws-cli is present
  yum:
    name: awscli
    state: latest

- name: ensure .aws exists
  file:
    path: '{{ jenkins_home }}/.aws'
    owner: '{{ jenkins_process_user }}'
    group: '{{ jenkins_process_user }}'
    mode: '0700'
    state: directory

- name: place config template
  template:
     src: config.j2
     dest: '{{ jenkins_home }}/.aws/config'
     owner: '{{ jenkins_process_user }}'
     group: '{{ jenkins_process_user }}'
     mode: '0600'

- name: place credentials template
  template:
     src: credentials.j2
     dest: '{{ jenkins_home }}/.aws/credentials'
     owner: '{{ jenkins_process_user }}'
     group: '{{ jenkins_process_user }}'
     mode: '0600'
