---

- set_fact:
    job_config: '~/jenkins/{{ jenkins_import_job }}.xml'

- jenkins_job:
    config: "{{ lookup('file', jenkins_import_job) }}"
    name: '{{ jenkins_import_job }]'
    url: http://localhost:8080
    user: '{{ jenkins_admin_username }}'
    password: '{{ jenkins_admin_password }}'
