---

- jenkins_job:
    config: "{{ lookup('file', '~/jenkins/config.xml') }}"
    name: IQSS-Dataverse-Develop
    url: http://localhost:8080
    user: '{{ jenkins_admin_username }}'
    password: '{{ jenkins_admin_password }}'
